services:
  - type: web
    name: ieee-event-backend
    env: node
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: "20.11.1"
      - key: MONGO_URI
        fromDatabase:
          name: ieee-event-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        generateValue: true

  - type: static
    name: ieee-event-frontend
    env: static
    rootDir: frontend/vite-project
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"

databases:
  - name: ieee-event-db
    databaseName: ieee_event
    user: ieee_event_user
